### ISSUE TITLE
Add app icon

### ISSUE THREAD

**Issue by Samridh29** [ACM-VIT/sticky-links#10]
Add app icon to `Assets.xcassets`

**Comment by nkhandelwal07** [comment]
Which app icon do you add?

**Comment by Samridh29** [comment]
Hello, @nkhandelwal07 thanks for showing interest in contributing to this repository. This issue is already being worked on, so you are welcome to work on any other issue of your choice.

**Comment by nkhandelwal07** [comment]
Sorry I do not have a design idea for the icon
