### ISSUE TITLE
Wrong category deleted when search is active

### ISSUE THREAD

**Issue by kevalvadoliya** [ACM-VIT/sticky-links#30]
1). The wrong category getting deleted when a search is active. It should delete what the user selected. 
2) Tableview displays all categories after clicking the delete button, It should display what the user searched. 
Please refer attached video.

https://user-images.githubusercontent.com/24249823/137576793-0cfc7e5e-8371-4f8e-8fd7-daaa8bf13983.mov

In the video, I was trying to delete the category `qwa` but `qwe` got deleted as `qwe` was in the first position.

**Comment by kevalvadoliya** [comment]
I would like to work on this issue? Could you please assign this to me? 
We can fix the same for `item` separately.

**Comment by Samridh29** [comment]
Same pr would do.
